root:
  path: 
  
server:
  port: 8880

spider:
  host: http://localhost
  port: 1024

tumblebug:
  host: http://localhost
  port: 1323
  username: default
  password: default

load:
  jmeter:
    dir: "/opt/ant/jmeter"
    version: 5.3

logging:
  level: info

database:
  driver: "sqlite"
  host: "${ROOT}/meta/ant_meta.db"
  port: 
  user:
  password:
  name:
