root:
  path: 
  
server:
  port: 8880

spider:
  host: http://localhost
  port: 1024

tumblebug:
  host: http://localhost
  port: 1323
  username: default
  password: default

load:
  retry: 2
  jmeter:
    dir: "/opt/ant/jmeter"
    version: 5.6

logging:
  level: info

database:
  driver: "postgres"
  host: "ant-postgres"
  port: "5432"
  user: "cm-ant-user"
  password: "cm-ant-secret"
  name: "cm-ant-db"
