spider:
  host: 127.0.0.1
  port: 1024

tumblebug:
  host: 127.0.0.1
  port: 1323
  username: default
  password: default

load:
  jmeter:
    workDir: "~/jmeter"
    version: 5.3

server:
  port: 8880

datasource:
  driver: "sqlite"
  connection: "${ROOT}/meta/ant_meta.db"
  username:
  password:
