version: '3.8'

services: 
  cb-spider:
    image: cloudbaristaorg/cb-spider:0.8.17
    container_name: cb-spider
    platform: linux/amd64
    ports:
      - "0.0.0.0:1024:1024"
      - "0.0.0.0:2048:2048"
    environment:
      - PLUGIN_SW=OFF
      # if you leave these values empty, REST Auth will be disabled.
      - API_USERNAME=
      - API_PASSWORD=
      - SPIDER_LOG_LEVEL=info


  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:0.8.12
    container_name: cb-tumblebug
    platform: linux/amd64
    ports:
      - "1323:1323"
    depends_on:
      - cb-spider
    volumes:
      - ./data/cb-tumblebug/meta_db/:/app/meta_db/
      - ./data/cb-tumblebug/log/:/app/log/
    environment:
      - SPIDER_REST_URL=http://cb-spider:1024/spider
      - API_USERNAME=default
      - API_PASSWORD=default
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:1323/tumblebug/readyz" ]
      interval: 10s
      timeout: 10s
      retries: 3

  cm-ant:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: cm-ant
    platform: linux/amd64
    ports:
        - 8880:8880
    depends_on:
      cb-tumblebug:
        condition: service_healthy
      ant-postgres:
        condition: service_healthy
    environment:
      - ANT_SPIDER_HOST=http://cb-spider
      - ANT_SPIDER_PORT=1024
      - ANT_TUMBLEBUG_HOST=http://cb-tumblebug
      - ANT_TUMBLEBUG_PORT=1323

  ant-postgres:
    image: postgres:16.2-alpine3.19
    environment:
      - POSTGRES_USER=cm-ant-user
      - POSTGRES_PASSWORD=cm-ant-secret
      - POSTGRES_DB=cm-ant-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "root", "-d", "mom_bank" ]
      interval: 3s
      timeout: 3s
      retries: 5